server:
  port: 8092

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, env, loggers, heapdump, threaddump 
  endpoint:
    health:
      show-details: always 
